---
apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: service
spec:
  type: NodePort
  selector:
    app: service
  ports:
  - protocol: TCP
    port: 8091
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  selector:
    matchLabels:
      app: service
  replicas: 1
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      - name: service
        image: devopswissen/service6:v1
        ports:
        - containerPort: 8090
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          timeoutSeconds: 1
